version: '3.4'

services:
  vinegarbot.discordbot:
    image: ${DOCKER_REGISTRY-}vinegarbotdiscordbot
    build:
      dockerfile: VinegarBot.DiscordBot/Dockerfile
    depends_on:
        - seq

  seq:
    image: datalust/seq:latest
    ports:
        - 8080:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata:
